### ISSUE TITLE
Problem with AKS cluster with non-admin kubeconfig

### ISSUE THREAD

**Issue by r0bnet** [mohatb/kubego#2]
When using an AKS cluster with "default" credentials then kubego doesn't seem to be able to authenticate. When using a cluster for which I got the admin credentials (`az aks get-credentials --admin...`) then it works perfectly fine.

This is the error message when I use with an AD authentication enabled cluster:
```sh
kubego
No Node selected, please select the node number..
panic: no Auth Provider found for name "azure"

goroutine 1 [running]:
main.getNodes()
	/home/abutaleb/kubego/main.go:122 +0x58b
main.main()
	/home/abutaleb/kubego/main.go:55 +0x33d
```

So I guess something on auth level fails but I didn't have time to investigate myself. If I'll be able to then I'm going to add this here.

**Comment by mohatb** [comment]
Hi Rob - I just tried it with AAD cluster but I am not able to repro. Could you please share the exact repro steps ?

**Comment by r0bnet** [comment]
Hey Mohammed,

1. I created a cluster with AAD authn/authz enabled. 
2. I'm using a group where my own account is member of as admin group
3. I'm getting the credentials with `az aks get-credentials -g <rg> -n <aks>`

Then I'm receiving the error above.

Here's the snippet of the TF code to create the cluster:
```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                    = "${var.prefix}-aks"
  location                = var.location
  resource_group_name     = azurerm_resource_group.rg.name
  dns_prefix              = "${var.prefix}aks"
  kubernetes_version      = var.kubernetes_version
  node_resource_group     = "${var.prefix}-aks-nodes-rg"
  private_cluster_enabled = true
  private_dns_zone_id     = var.private_dns_zone_id

  role_based_access_control {
    enabled = true

    azure_active_directory {
      managed                = true
      azure_rbac_enabled     = true
      admin_group_object_ids = var.admin_group_object_ids
    }
  }

  default_node_pool {
    type                 = "VirtualMachineScaleSets"
    name                 = "default"
    vm_size              = var.worker_size
    os_disk_size_gb      = 128
    vnet_subnet_id       = var.subnet_id
    enable_auto_scaling  = true
    node_count           = var.worker_count
    min_count            = var.min_worker_count
    max_count            = var.max_worker_count
    orchestrator_version = var.kubernetes_version
    availability_zones   = var.enable_availability_zones ? ["1", "2", "3"] : null
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Standard"
    network_policy    = "calico"
    outbound_type     = "userDefinedRouting"
  }

  identity {
    type                      = "UserAssigned"
    user_assigned_identity_id = azurerm_user_assigned_identity.managed_identity.id
  }

  addon_profile {
    azure_keyvault_secrets_provider {
      enabled = true
    }
  }
}
```

Hope this helps.

**Comment by mohatb** [comment]
This should be fixed now by adding the auth package to support AKS and other cloud providers https://pkg.go.dev/k8s.io/client-go/plugin/pkg/client/auth.

@r0bnet could you please test the last bin and verify ?

**Comment by r0bnet** [comment]
Sorry for the late reply but now I don't have any issues anymore. Thanks for the fix :)
